//https://projecteuler.net/problem=12

/*The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?*/

#include "stdafx.h"
#include <iostream>
using namespace std;

int prirozene = 2, triangle = 1;

bool ma500Delitelu() {
	int pocetDelitelu = 2, cinitelA = 1, cinitelB = triangle;
	while (cinitelA < cinitelB) {
		cinitelA++;
		if (triangle % cinitelA == 0) {
			pocetDelitelu += 2;
			cinitelB = triangle / cinitelA;
		}
	} 
	return pocetDelitelu > 500;
}


int main() {
	while (!ma500Delitelu()) 
		triangle += prirozene++;
	cout << triangle << endl;
    return 0;
}

